{
 "title": "IoT Inventory",
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "rate(flask_request_total[1m])" }
   ]
  },
  {
   "title": "Stock events per minute",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "targets": [
    {
     "expr": "rate(stock_events_total[1m]) * 60"
    }
   ]
  },
  {
   "title": "Alerts (count)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 16, "h": 8 },
   "targets": [
    { "expr": "increase(alerts_total[15m])" }
   ]
  }
 ]
}